# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\ImageZhuo\ui\HistogramDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistogramDisplay(object):
    def setupUi(self, HistogramDisplay):
        HistogramDisplay.setObjectName("HistogramDisplay")
        HistogramDisplay.resize(432, 324)
        HistogramDisplay.setSizeGripEnabled(True)
        self.lbl_display = QtWidgets.QLabel(HistogramDisplay)
        self.lbl_display.setGeometry(QtCore.QRect(8, 8, 72, 15))
        self.lbl_display.setObjectName("lbl_display")

        self.retranslateUi(HistogramDisplay)
        QtCore.QMetaObject.connectSlotsByName(HistogramDisplay)

    def retranslateUi(self, HistogramDisplay):
        _translate = QtCore.QCoreApplication.translate
        HistogramDisplay.setWindowTitle(_translate("HistogramDisplay", "灰度直方图显示 / ImageZhuo"))
        self.lbl_display.setText(_translate("HistogramDisplay", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistogramDisplay = QtWidgets.QDialog()
    ui = Ui_HistogramDisplay()
    ui.setupUi(HistogramDisplay)
    HistogramDisplay.show()
    sys.exit(app.exec_())
