# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\ImageZhuo\ui\ImageDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setSizeGripEnabled(True)
        self.lbl_display = ImageDisplayWidget(Dialog)
        self.lbl_display.setGeometry(QtCore.QRect(2, 2, 160, 15))
        self.lbl_display.setObjectName("lbl_display")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "图像显示 / ImageZhuo"))
        self.lbl_display.setText(_translate("Dialog", "[IMAGE DISPLAY AREA]"))
from ImageDisplayWidget import ImageDisplayWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
