# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\ImageZhuo\ui/WaitDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitDialog(object):
    def setupUi(self, WaitDialog):
        WaitDialog.setObjectName("WaitDialog")
        WaitDialog.resize(432, 40)
        WaitDialog.setSizeGripEnabled(True)

        self.retranslateUi(WaitDialog)
        QtCore.QMetaObject.connectSlotsByName(WaitDialog)

    def retranslateUi(self, WaitDialog):
        _translate = QtCore.QCoreApplication.translate
        WaitDialog.setWindowTitle(_translate("WaitDialog", "操作进行中，请耐心等待..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaitDialog = QtWidgets.QDialog()
    ui = Ui_WaitDialog()
    ui.setupUi(WaitDialog)
    WaitDialog.show()
    sys.exit(app.exec_())
